CREATE DATABASE DBLAB;


CREATE TABLE USUARIO(
IDUSUARIO INT IDENTITY(1,1) PRIMARY KEY,
NOMBRES VARCHAR(225),
APELLIDOS VARCHAR(255),
PASSWORD VARCHAR(75),
USUARIO VARCHAR(45),
ESTADO VARCHAR(2),
FECHANACIMIENTO DATE,
CAMBIOCONTRASENA VARCHAR(2),
DESCRIPCION VARCHAR(255),
FECHACREACION DATE,
USUARIOCREACION VARCHAR(45),
FECHAACTUALIZACION DATE,
USAURIOACTUALIZACION VARCHAR(45)
);



CREATE TABLE ROL(
IDROL INT IDENTITY(1,1) PRIMARY KEY,
NOMBRE VARCHAR(125),
DESCRIPCION VARCHAR(255),
FECHACREACION DATE,
USUARIOCREACION VARCHAR(45)
);

CREATE TABLE ROLUSUARIO(
IDROL INT,
IDUSUARIO INT,
FOREIGN KEY(IDROL) REFERENCES ROL(IDROL),
FOREIGN KEY(IDUSUARIO) REFERENCES USUARIO(IDUSUARIO)
);


CREATE TABLE FORMULARIO(
IDFORMULARIO INT IDENTITY(1,1) PRIMARY KEY,
NOBRE VARCHAR(125),
DESCRIPCION VARCHAR(255),
FECHACREACION DATE DEFAULT ''
);

CREATE TABLE ACCESOFORULARIO(
IDROL INT,
IDFORMULARIO INT,
FOREIGN KEY(IDROL) REFERENCES ROL(IDROL),
FOREIGN KEY(IDFORMULARIO) REFERENCES FORMULARIO(IDFORMULARIO)
);


CREATE TABLE MUESTRA(
IDMUESTRA INT IDENTITY(1,1) PRIMARY KEY,
DESCRIPCION VARCHAR(255),
FECHACREACION DATE,
USUARIOCREACION VARCHAR(45),
FECHAMODIFICACION DATE,
USUARIOMODIFICACION VARCHAR(25)
);



CREATE TABLE PACIENTE(
IDPACIENTE INT IDENTITY(1,1) PRIMARY KEY,
NOMBRES VARCHAR(90),
APELLIDOS VARCHAR(125),
FECHANACIIENTO DATE,
TELEFONO VARCHAR(9),
DIRECCION VARCHAR(255),
FECHACREACION DATE,
USUARIOCREACION VARCHAR(45),
FECHAMODIFICACION DATE,
USUARIOODIFICACION VARCHAR(45)
);


CREATE TABLE TIPO_ANALISIS(
IDTIPO_ANALISIS INT IDENTITY(1,1) PRIMARY KEY,
DESCRIPCION VARCHAR(255),
IDMUESTRA INT,
FECHACREACION DATE,
USUARIOCREACION VARCHAR(45),
FECHAMODIFICACION DATE,
USUARIOMODIFICACION VARCHAR(45),
FOREIGN KEY(IDMUESTRA) REFERENCES MUESTRA(IDMUESTRA)
);


CREATE TABLE TIPO_RESULTADO(
IDTIPO_RESULTADO INT IDENTITY(1,1) PRIMARY KEY,
DESCRIPCION VARCHAR(30),
IDTIPO_ANALISIS INT,
FECHACREACION DATE,
USUARIOCREACION VARCHAR(45),
FECHAMODIFICACION DATE,
USUARIOMODIFICACION VARCHAR(45),
FOREIGN KEY(IDTIPO_ANALISIS) REFERENCES TIPO_ANALISIS(IDTIPO_ANALISIS)
);


CREATE TABLE RESULTADO(
IDRESULTADO INT IDENTITY(1,1) PRIMARY KEY,
DESCRIPCION VARCHAR(75),
VALORNORMAL VARCHAR(75),
TIPOMEDIDA VARCHAR(75),
IDTIPO_RESULTADO INT,
FECHACREACION DATE,
USUARIOCREACION VARCHAR(45),
FECHAMODIFICACION DATE,
USUARIOMODIFICACION VARCHAR(45),
FOREIGN KEY(IDTIPO_RESULTADO) REFERENCES TIPO_RESULTADO(IDTIPO_RESULTADO)
);


CREATE TABLE ANALISIS(
IDANALISIS INT IDENTITY(1,1) PRIMARY KEY,
FECHA DATE, 
ESTADO VARCHAR(2),
IDPACIENTE INT,
IDMUESTRA INT,
FECHACREACION DATE,
USUARIOCREACION VARCHAR(45),
FECHAMODIFICACION DATE,
USUARIOMODIFICACION VARCHAR(45)
FOREIGN KEY(IDPACIENTE) REFERENCES PACIENTE(IDPACIENTE),
FOREIGN KEY(IDMUESTRA) REFERENCES MUESTRA(IDMUESTRA)
);


CREATE TABLE ANALISIS_TIPO_ANALISIS(
IDANALISIS INT,
IDTIPO_ANALISIS INT,
FOREIGN KEY(IDANALISIS) REFERENCES ANALISIS(IDANALISIS),
FOREIGN KEY(IDTIPO_ANALISIS) REFERENCES TIPO_ANALISIS(IDTIPO_ANALISIS)
);



CREATE TABLE RESULTADO_ANALISIS(
IDANALISIS INT,
IDRESULTADO INT,
FOREIGN KEY(IDANALISIS) REFERENCES ANALISIS(IDANALISIS),
FOREIGN KEY(IDRESULTADO) REFERENCES RESULTADO(IDRESULTADO)
);




FECHACREACION DATE,
USUARIOCREACION VARCHAR(45),
FECHAMODIFICACION DATE,
USUARIOMODIFICACION VARCHAR(45)



ALTER TABLE RESULTADO ALTER COLUMN FECHACREACION DATETIME

